server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

  - job_name: nginx_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/access.log

    pipeline_stages:
      - regex:
          expression: '^(?P<ip>\S+) - \S+ \[(?P<time>[^\]]+)\] "(?P<method>\S+) (?P<path>\S+) (?P<protocol>[^"]+)" (?P<status>\d{3}) (?P<size>\d+) "(?P<referer>[^"]*)" "(?P<agent>[^"]*)"'

      - labels:
          ip:
          method:
          status:
          path:

      # normalize route (VERY IMPORTANT for Grafana grouping)
      - replace:
          source: path
          target: route
          expression: "([a-zA-Z0-9/_-]+).*"

      - labels:
          route:

      - drop:
          source: path
          expression: ".*/health.*"

  - job_name: nginx_error_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_errors
          __path__: /var/log/nginx/error.log

    pipeline_stages:
      - regex:
          expression: '^(?P<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\] (?P<pid>\d+)#(?P<tid>\d+): \*?(?P<conn>\d*) ?(?P<message>.+)'

      - labels:
          level: